### ISSUE TITLE
NzbToMedia - Error Python2 - No such file or directory

### ISSUE THREAD

**Issue by ajongsma** [ajongsma/OSX_MediaCenter#6]
env: python2: No such file or directory

**Comment by ajongsma** [comment]
sudo ln -sf /usr/bin/python2.7 /usr/local/bin/python2

**Comment by nbara** [comment]
FWIW this does not work in El Capitan

**Comment by ajongsma** [comment]
It found another solution by disabling SIP, but I dislike such a method to resolve this issue.
